### ISSUE TITLE
yoo

### ISSUE THREAD

**Issue by bubzilla** [lunakittyyy/Melontilla#1]
sorry to bother you with my notifications but it would be really cool if you maintained this, ive never heard of anything for gorilla tag and melonloader other then this. anyways i just think this idea is cool.
![drake](https://github.com/user-attachments/assets/d1eb017e-ea39-4368-80c0-9e1edc7f198e)

**Comment by gizmogoat** [comment]
this project is very low maintenance & it's mostly just the code from the bepinex version so i might come back to it

**Comment by bubzilla** [comment]
TYYYYY
